### ISSUE TITLE
Incompatibility with Iris + Sodium

### ISSUE THREAD

**Issue by Rairun** [Benjamin-Norton/BetterBookshelves#9]
I use Iris + Sodium for shader support. This is my mod list:

fabric-api-0.89.3+1.20.2.jar
**iris-mc1.20.2-1.6.9.jar
sodium-fabric-mc1.20.2-0.5.3.jar**
modmenu-8.0.0.jar
yet-another-config-lib-fabric-3.2.1+1.20.2.jar
**betterbookshelves-1.0.0.jar**

If I remove Iris + Sodium, BetterBookshelves works. If I remove BetterBookshelves, Iris + Sodium work. Together, I get the following crash message and exit code:

The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null

Exit code: -1073740791

**Comment by Bawnorton** [comment]
Install Indium, it's needed for mods that use fabric's rendering api when you're using sodium
